name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["PredictMobile/2"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report! Please remember this ticket is public so do not include any sensitive information**
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product are you reporting an issue with?
      options:
        - Sensabill
        - Predict
        - Both
  - type: textarea
    id: what
    attributes:
      label: Describe the bug?
      description: Please give a clear and concise description of what the bug is. Add screenshots if possible.
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How To Reproduce?
      description: Please detail steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Please give a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Checked for existing ticket
      options:
        - label: I confirm I have checked to see that my issue has not already been reported.
          required: true
        - label: I confirm I have not included any sensitive information.
          required: true